Completed prep-javascript-objects exercise.
samlee0258/prep-1122-code-solutions pull request #11
Opened 2022-11-22 20:47 UTC by samlee0258

<img width="782" alt="Screenshot 2022-11-22 at 12 45 27 PM" src="https://user-images.githubusercontent.com/110208589/203418129-d4fac98a-eda4-4163-9e64-3e219f4c26e7.png">

2022-11-22 22:28 UTC, thebearingedge requested changes

2022-11-22 22:28 UTC, thebearingedge commented on prep-javascript-objects/main.js
> +var fullName = 'Samuel ' + 'Lee';
We can create the `fullName` by getting the `firstName` and `lastName` of the `person` object.

```js
var fullName = person.firstName + ' ' + person.lastName;
```

2022-11-23 01:24 UTC, samlee0258 commented on prep-javascript-objects/main.js
> +var fullName = 'Samuel ' + 'Lee';
<img width="810" alt="Screenshot 2022-11-22 at 5 22 48 PM" src="https://user-images.githubusercontent.com/110208589/203452693-431454c3-5e40-461f-b803-121732b3a73a.png">

2022-11-23 01:25 UTC, samlee0258 commented on prep-javascript-objects/main.js
> +var fullName = 'Samuel ' + 'Lee';
<img width="617" alt="Screenshot 2022-11-22 at 5 25 21 PM" src="https://user-images.githubusercontent.com/110208589/203452768-ba860e8b-939e-4057-b2dc-7e4d21f7a1e7.png">

2022-11-23 02:14 UTC, thebearingedge approved these changes

2022-11-23 02:23 UTC, merged